version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - PORT=3000
      - WSPORT=8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
